### ISSUE TITLE
Building SPA into existing web site

### ISSUE THREAD

**Issue by Bikeman868** [vvvv/Posh#16]
I really like what you are doing with this project, but I want to include this on some pages of an existing web site. Have you considered writing the Posh server as OWIN middleware?

**Comment by joreg** [comment]
i'm afraid we're not familiar with OWIN and also don't have any plans at the moment to continue working on POSH

**Comment by Bikeman868** [comment]
My description of OWIN is here https://github.com/Bikeman868/OwinFramework/wiki/OWIN

Essentially OWIN is an abstraction of the web hosting software (Apache, IIS etc). If you modified your POSH server to run on top of OWIN then users of POSH could run self-hosted (like your demo) or they could run it on IIS, Apache or any other hosting platform.
